### ISSUE TITLE
Add script to Upgrade chaincode

### ISSUE THREAD

**Issue by kosullivansita** [sitalab/FlightChain#2] opened 2018-07-25 16:01 UTC
Right now, when changing the chaincode, the whole network needs to be brought down & restarted. We need to add an option to just upgrade the chaincode.

See some info here on this: 
http://hyperledger-fabric.readthedocs.io/en/latest/channel_update_tutorial.html#upgrade-and-invoke

It *seems* straightforward...

BTW - This script should go in the chaincode folder

**Comment by sinead-kelly** [comment] 2018-08-09 13:17
Getting an error when upgrade script attempts to install new chaincode
```
Error response from daemon: Container 957727fec406d558cce46f387a64652483fa6c905138c064719b319dd949b918 is not running
upgrading flightchain to version 1.1
2018-08-08 06:45:09.927 EDT [main] main -> ERRO 001 Fatal error when initializing core config : error when reading core config file: Unsupported Config Type ""
```
Online solutions suggest to export FABRIC_CFG_PATH but this hasn't worked

**Comment by sinead-kelly** [comment] 2018-08-10 08:25
config error was caused by missing environment variable in docker exec command, fixed now.

**Comment by sinead-kelly** [comment] 2018-08-10 08:39
```
upgrading flightchain to version 1.1
2018-08-10 08:38:31.321 UTC [chaincodeCmd] InitCmdFactory -> INFO 001 Get chain(mychannel) orderer endpoint: orderer.example.com:7050
2018-08-10 08:38:31.324 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default escc
2018-08-10 08:38:31.324 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 003 Using default vscc
Error: Error endorsing chaincode: rpc error: code = Unknown desc = chaincode error (status: 500, message: could not find chaincode with name 'flightchain')
```

**Comment by sinead-kelly** [comment] 2018-08-14 11:25
pulled latest from master as my local was out of date but now getting a different error:
```
Error: Error getting broadcast client: orderer client failed to connect to orderer.example.com:7050: failed to create new connection: context deadline exceeded
```
Orderer is up and running on port 7050

**Comment by sinead-kelly** [comment] 2018-08-14 13:34
@kosullivansita according to the hyperledger docs "since multiple versions of a chaincode may be active simultaneously, the upgrade process doesn’t automatically remove the old versions, so user must manage this for the time being."
So we'll have to remove old chaincodes ourselves

**Closed** 2018-08-14 14:32 UTC

**Comment by sinead-kelly** [comment] 2018-08-14 14:39
the upgrade transaction only affects one channel at a time, the channel to which the transaction is submitted. So if you want to upgrade a chaincode that is on multiple channels you will have to do it for each channel
